apiVersion: v1
kind: Pod
metadata:
  name: vote-pod
  labels:
    name: vote-pod
    app: demo-voting-app
spec:
  containers:
    - name: vote-pod
      image: kodekloud/examplevotingapp_vote:v1
      ports: 
        - containerPort: 80








